### ISSUE TITLE
Support for Spring Boot 4

### ISSUE THREAD

**Issue by robert-hoglund** [jdbc-observations/datasource-micrometer#78]
Are there plans to provide a version of datasource-micrometer that is compatible with Spring Boot 4, micrometer 1.16 and micrometer-tracing 1.6?
Would be great to get a Milestone releases of datasource-micrometer that is compatible with Spring Boot 4 milestones and release candidates if possible.

**Comment by ttddyy** [comment]
@robert-hoglund Thanks for the suggestion.
Due to the package changes(new modular design) in Spring Boot 4, I don't think the existing datasource-micrometer works with Boot 4.
It's a good idea to release a new version that works with Spring Boot 4 milestones.
Let me think about versioning and resolve the Spring Boot upgrade.

**Comment by ttddyy** [comment]
I’ve created a [boot-4 branch](https://github.com/jdbc-observations/datasource-micrometer/tree/boot-4) and committed an upgrade to Spring Boot `4.0.0-M2`.
The change simply updated dependencies and fixed compilation errors so far.
If you want to do a quick check, you can build the jars locally from the branch.

**Comment by robert-hoglund** [comment]
Thanks for the update.
I've tried it out locally and it worked fine after I updated the versions for micrometer-bom, micrometer-tracing-bom to align with Spring Boot 4 miltestone dependencies. 
I also updated spring-core to align with Spring 7 and took the opportunity to update other dependencies to latest version.
See PR https://github.com/jdbc-observations/datasource-micrometer/pull/80

**Comment by goafabric** [comment]
Just stumbled upon this issue
When bootstrapping with Boot 4.0 M2/M3 the following error occurs

'
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.observation.ObservationAutoConfiguration
'

This is most likely because the AutoConfiguration was moved to
org.springframework.boot.micrometer.observation.autoconfigure.ObservationAutoConfiguration

Will the version increases from the PR also resolve this ?

**Comment by robert-hoglund** [comment]
Thanks for the update.
Can you please update the dependencies for micrometer and micrometer-tracing.
Spring Boot 4 has updated to micrometer 1.16 and micrometer-tracing 1.6
There are milestone builds for micrometer with the same naming as Spring Boot.
So we need to use 1.16.0-M3 and 1.6.0-M3 to align with Spring Boot 4.0.0-M3.

**Comment by robert-hoglund** [comment]
> I just released datasource-micrometer `2.0.0-RC1`, which works with Spring Boot `4.0.0-M3`.

Thanks, I've tried it out and it works well in my test project 👍
